#!/bin/sh
# Copyright 2026 VKrishna04
# SPDX-License-Identifier: Apache-2.0
#
# Regenerate the Homebrew formula, the Scoop manifest and the WinGet manifests for one
# published release.
#
# Every one of these three formats is the same three facts in a different syntax: a
# download URL, a SHA-256, and a version. All three are already published — the release
# workflow writes a `.sha256` sidecar beside every asset — so nothing here computes a
# hash, it reads the ones that were attested. Hand-maintaining three copies of the same
# seven checksums is how a package manager ends up installing last month's binary.
#
#   sh scripts/render-packaging.sh 1.4.0 [dist-dir]
#
# With a directory, the sidecars are read from it (the release job already has them).
# Without one, they are downloaded from the release, which is how this is re-run by hand
# for a release that has already shipped.

set -eu

version="${1:-}"
dist="${2:-}"
if [ -z "$version" ]; then
	echo "usage: sh scripts/render-packaging.sh <version> [dist-dir]" >&2
	exit 2
fi

repo="Life-Experimentalist/dev-prune"
base="https://github.com/$repo/releases/download/v$version"
root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
out="$root/packaging"

# The digest for one asset, from the sidecar published beside it. `sha256sum` format is
# the digest, two spaces, the file name — the first field is the whole of it.
digest() {
	if [ -n "$dist" ]; then
		cut -d' ' -f1 <"$dist/$1.sha256"
	else
		curl -fsSL "$base/$1.sha256" | cut -d' ' -f1
	fi
}

mac_x64=$(digest "dev-prune-v$version-darwin-x64.tar.gz")
mac_arm=$(digest "dev-prune-v$version-darwin-arm64.tar.gz")
linux_x64=$(digest "dev-prune-v$version-linux-x64.tar.gz")
linux_arm=$(digest "dev-prune-v$version-linux-arm64.tar.gz")
win_x64=$(digest "dev-prune-v$version-windows-x64.zip")
win_arm=$(digest "dev-prune-v$version-windows-arm64.zip")
win_x86=$(digest "dev-prune-v$version-windows-x86.zip")

mkdir -p "$out/homebrew" "$out/scoop" "$out/winget"

# --- Homebrew -------------------------------------------------------------------------
# A formula, not a cask: casks are for prebuilt macOS app bundles, and this is a plain
# binary that also has to work on Linux, where casks do not exist at all.
cat >"$out/homebrew/dev-prune.rb" <<EOF
# Copyright 2026 VKrishna04
# SPDX-License-Identifier: Apache-2.0
#
# Generated by scripts/render-packaging.sh — edit that, not this.
class DevPrune < Formula
  desc "Universal, lockfile-safe workspace pruner and background dependency cleaner"
  homepage "https://devprune.vkrishna04.me"
  version "$version"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "$base/dev-prune-v$version-darwin-arm64.tar.gz"
      sha256 "$mac_arm"
    else
      url "$base/dev-prune-v$version-darwin-x64.tar.gz"
      sha256 "$mac_x64"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "$base/dev-prune-v$version-linux-arm64.tar.gz"
      sha256 "$linux_arm"
    else
      url "$base/dev-prune-v$version-linux-x64.tar.gz"
      sha256 "$linux_x64"
    end
  end

  def install
    bin.install "dev-prune"
    # The two names are one binary, and every integration dev-prune writes down — the
    # git hooks, the scheduler — records the path it was invoked from. Installing only
    # one name would make \`devp\` fail for anyone who read the README.
    bin.install_symlink bin/"dev-prune" => "devp"
    generate_completions_from_executable(bin/"dev-prune", "completions")
  end

  test do
    # \`DEV_PRUNE_NO_AUTO_SETUP\` because nothing may install itself during a formula
    # test: Homebrew's sandbox would fail the build, and a test that registers a
    # scheduled task on someone's machine is worse than no test at all.
    ENV["DEV_PRUNE_NO_AUTO_SETUP"] = "1"
    assert_match version.to_s, shell_output("#{bin}/dev-prune --version")
    assert_match version.to_s, shell_output("#{bin}/devp --version")
  end
end
EOF

# --- Scoop ----------------------------------------------------------------------------
# `checkver`/`autoupdate` let Scoop bump this without waiting for a release job: the
# bucket's own updater reads the latest tag and rewrites the hashes from the sidecars.
cat >"$out/scoop/dev-prune.json" <<EOF
{
    "##": [
        "Copyright 2026 VKrishna04",
        "SPDX-License-Identifier: Apache-2.0",
        "Generated by scripts/render-packaging.sh — edit that, not this."
    ],
    "version": "$version",
    "description": "Universal, lockfile-safe workspace pruner and background dependency cleaner",
    "homepage": "https://devprune.vkrishna04.me",
    "license": "Apache-2.0",
    "architecture": {
        "64bit": {
            "url": "$base/dev-prune-v$version-windows-x64.zip",
            "hash": "$win_x64"
        },
        "arm64": {
            "url": "$base/dev-prune-v$version-windows-arm64.zip",
            "hash": "$win_arm"
        },
        "32bit": {
            "url": "$base/dev-prune-v$version-windows-x86.zip",
            "hash": "$win_x86"
        }
    },
    "bin": [
        "dev-prune.exe",
        [
            "dev-prune.exe",
            "devp"
        ]
    ],
    "checkver": {
        "github": "https://github.com/$repo"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/$repo/releases/download/v\$version/dev-prune-v\$version-windows-x64.zip"
            },
            "arm64": {
                "url": "https://github.com/$repo/releases/download/v\$version/dev-prune-v\$version-windows-arm64.zip"
            },
            "32bit": {
                "url": "https://github.com/$repo/releases/download/v\$version/dev-prune-v\$version-windows-x86.zip"
            }
        },
        "hash": {
            "url": "\$url.sha256"
        }
    }
}
EOF

# --- WinGet ---------------------------------------------------------------------------
# Three files, because that is what `winget-pkgs` validates: the version manifest names
# the other two, the installer manifest carries the URLs and hashes, and the locale
# manifest carries everything a human reads. A zip with `NestedInstallerType: portable`
# is how a plain binary ships — there is no installer to run and nothing to uninstall
# beyond removing the file.
#
# Each file opens with the `yaml-language-server` schema line as well: `winget validate`
# reports "Schema header not found" without it, and that warning is an exit code 40, which
# a release job reads as a failure.
wg="$out/winget"
cat >"$wg/VKrishna04.dev-prune.yaml" <<EOF
# Copyright 2026 VKrishna04
# SPDX-License-Identifier: Apache-2.0
#
# Generated by scripts/render-packaging.sh — edit that, not this.
# yaml-language-server: \$schema=https://aka.ms/winget-manifest.version.1.12.0.schema.json
PackageIdentifier: VKrishna04.dev-prune
PackageVersion: $version
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.12.0
EOF

# One `NestedInstallerFiles` entry per architecture, not two. WinGet rejects a second
# entry that repeats a `RelativeFilePath` — "Duplicate relative file path found", and
# `winget validate` exits 41 — so a portable install can publish only one name from a
# single-file archive. It publishes `dev-prune`; the `devp` twin appears on first run,
# when the binary installs its managed pair on PATH.
cat >"$wg/VKrishna04.dev-prune.installer.yaml" <<EOF
# Copyright 2026 VKrishna04
# SPDX-License-Identifier: Apache-2.0
#
# Generated by scripts/render-packaging.sh — edit that, not this.
# yaml-language-server: \$schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: VKrishna04.dev-prune
PackageVersion: $version
InstallerType: zip
NestedInstallerType: portable
Commands:
  - dev-prune
  - devp
ReleaseDate: $(date -u +%Y-%m-%d)
Installers:
  - Architecture: x64
    InstallerUrl: $base/dev-prune-v$version-windows-x64.zip
    InstallerSha256: $win_x64
    NestedInstallerFiles:
      - RelativeFilePath: dev-prune.exe
        PortableCommandAlias: dev-prune
  - Architecture: arm64
    InstallerUrl: $base/dev-prune-v$version-windows-arm64.zip
    InstallerSha256: $win_arm
    NestedInstallerFiles:
      - RelativeFilePath: dev-prune.exe
        PortableCommandAlias: dev-prune
  - Architecture: x86
    InstallerUrl: $base/dev-prune-v$version-windows-x86.zip
    InstallerSha256: $win_x86
    NestedInstallerFiles:
      - RelativeFilePath: dev-prune.exe
        PortableCommandAlias: dev-prune
ManifestType: installer
ManifestVersion: 1.12.0
EOF

cat >"$wg/VKrishna04.dev-prune.locale.en-US.yaml" <<EOF
# Copyright 2026 VKrishna04
# SPDX-License-Identifier: Apache-2.0
#
# Generated by scripts/render-packaging.sh — edit that, not this.
# yaml-language-server: \$schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json
PackageIdentifier: VKrishna04.dev-prune
PackageVersion: $version
PackageLocale: en-US
Publisher: VKrishna04
PublisherUrl: https://github.com/Life-Experimentalist
PublisherSupportUrl: https://github.com/$repo/issues
PackageName: dev-prune
PackageUrl: https://devprune.vkrishna04.me
License: Apache-2.0
LicenseUrl: https://github.com/$repo/blob/main/LICENSE.md
ShortDescription: Universal, lockfile-safe workspace pruner and background dependency cleaner
Description: >-
  dev-prune reclaims disk space from Git repositories you have stopped working in by
  deleting the dependency and build directories a lockfile can rebuild — node_modules,
  .venv, target, vendor and the rest — and refuses to delete anything it cannot prove is
  recoverable. It verifies the lockfile before it touches a directory, never crosses a
  .git boundary, never follows a symlink, and records every deletion so devp restore can
  put it back.
Moniker: dev-prune
Tags:
  - cli
  - cleanup
  - disk-space
  - node-modules
  - developer-tools
ReleaseNotesUrl: https://github.com/$repo/releases/tag/v$version
ManifestType: defaultLocale
ManifestVersion: 1.12.0
EOF

echo "Rendered packaging manifests for v$version:"
find "$out" -type f | sed "s|^$root/|  |"
