# Copyright 2026 VKrishna04
# SPDX-License-Identifier: Apache-2.0
#
# Generated by scripts/render-packaging.sh — edit that, not this.
class DevPrune < Formula
  desc "Universal, lockfile-safe workspace pruner and background dependency cleaner"
  homepage "https://devprune.vkrishna04.me"
  version "1.8.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Life-Experimentalist/dev-prune/releases/download/v1.8.0/dev-prune-v1.8.0-darwin-arm64.tar.gz"
      sha256 "b499e47a1161d1f59c9c4e40f0414c39d8665984d657d0d666ffbf0ac68d33fc"
    else
      url "https://github.com/Life-Experimentalist/dev-prune/releases/download/v1.8.0/dev-prune-v1.8.0-darwin-x64.tar.gz"
      sha256 "41742cd233b2045acf2b8ff89db9bbc651b478c27c81915d0932fc3d75d2fb38"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/Life-Experimentalist/dev-prune/releases/download/v1.8.0/dev-prune-v1.8.0-linux-arm64.tar.gz"
      sha256 "ae8daa2cf1e07b6fde0e2be3c5271ca605ba9f4fd369041352a1762d2ceba781"
    else
      url "https://github.com/Life-Experimentalist/dev-prune/releases/download/v1.8.0/dev-prune-v1.8.0-linux-x64.tar.gz"
      sha256 "9a6109dbb4f6f94a92e5ce79783c1ce9ccd2eb9b4c7bd7fff581aebcaa8c6a3d"
    end
  end

  def install
    bin.install "dev-prune"
    # The two names are one binary, and every integration dev-prune writes down — the
    # git hooks, the scheduler — records the path it was invoked from. Installing only
    # one name would make `devp` fail for anyone who read the README.
    bin.install_symlink bin/"dev-prune" => "devp"
    generate_completions_from_executable(bin/"dev-prune", "completions")
  end

  test do
    # `DEV_PRUNE_NO_AUTO_SETUP` because nothing may install itself during a formula
    # test: Homebrew's sandbox would fail the build, and a test that registers a
    # scheduled task on someone's machine is worse than no test at all.
    ENV["DEV_PRUNE_NO_AUTO_SETUP"] = "1"
    assert_match version.to_s, shell_output("#{bin}/dev-prune --version")
    assert_match version.to_s, shell_output("#{bin}/devp --version")
  end
end
