# Copyright 2026 VKrishna04
# SPDX-License-Identifier: Apache-2.0
#
# Generated by scripts/render-packaging.sh — edit that, not this.
class DevPrune < Formula
  desc "Universal, lockfile-safe workspace pruner and background dependency cleaner"
  homepage "https://devprune.vkrishna04.me"
  version "1.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Life-Experimentalist/dev-prune/releases/download/v1.4.0/dev-prune-v1.4.0-darwin-arm64.tar.gz"
      sha256 "c3c2b4541fe8df727d795f573222ebf64f6adf8a99779cc57ebcf7ac5c389309"
    else
      url "https://github.com/Life-Experimentalist/dev-prune/releases/download/v1.4.0/dev-prune-v1.4.0-darwin-x64.tar.gz"
      sha256 "91ac64d86147384e7cd4300c2a9124e492d57225b7c1d2a3eaa0f942ed2888d5"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/Life-Experimentalist/dev-prune/releases/download/v1.4.0/dev-prune-v1.4.0-linux-arm64.tar.gz"
      sha256 "2a8a97086e3bacbf2ff1b952e42663c1b02646e5cf108e0c17c63465bd0228a8"
    else
      url "https://github.com/Life-Experimentalist/dev-prune/releases/download/v1.4.0/dev-prune-v1.4.0-linux-x64.tar.gz"
      sha256 "f7d87a1303c73e6be116fde840192a76a655b9bca65bff3baa94a0fcf63c32c2"
    end
  end

  def install
    bin.install "dev-prune"
    # The two names are one binary, and every integration dev-prune writes down — the
    # git hooks, the scheduler — records the path it was invoked from. Installing only
    # one name would make `devp` fail for anyone who read the README.
    bin.install_symlink bin/"dev-prune" => "devp"
    generate_completions_from_executable(bin/"dev-prune", "completions")
  end

  test do
    # `DEV_PRUNE_NO_AUTO_SETUP` because nothing may install itself during a formula
    # test: Homebrew's sandbox would fail the build, and a test that registers a
    # scheduled task on someone's machine is worse than no test at all.
    ENV["DEV_PRUNE_NO_AUTO_SETUP"] = "1"
    assert_match version.to_s, shell_output("#{bin}/dev-prune --version")
    assert_match version.to_s, shell_output("#{bin}/devp --version")
  end
end
