# Copyright 2026 VKrishna04
# SPDX-License-Identifier: Apache-2.0
#
# Generated by scripts/render-packaging.sh — edit that, not this.
class DevPrune < Formula
  desc "Universal, lockfile-safe workspace pruner and background dependency cleaner"
  homepage "https://devprune.vkrishna04.me"
  version "1.4.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Life-Experimentalist/dev-prune/releases/download/v1.4.1/dev-prune-v1.4.1-darwin-arm64.tar.gz"
      sha256 "d0e290c3c2dad4bdba400428a8303f9bc6c2e1bab173bb755fab85f81d234dba"
    else
      url "https://github.com/Life-Experimentalist/dev-prune/releases/download/v1.4.1/dev-prune-v1.4.1-darwin-x64.tar.gz"
      sha256 "1d56b79f5a95f3ba2f44ca2967e17e8d6a7297349b924ae7b508f808be27017a"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/Life-Experimentalist/dev-prune/releases/download/v1.4.1/dev-prune-v1.4.1-linux-arm64.tar.gz"
      sha256 "5c91434c2a7bb8c18ef5ecd36ae7b8323dd5eda84ee43bb21d5b3f05eb69d6b9"
    else
      url "https://github.com/Life-Experimentalist/dev-prune/releases/download/v1.4.1/dev-prune-v1.4.1-linux-x64.tar.gz"
      sha256 "c4be31fcb3a4696abf5a3891c8238db67c520b232da05dcba692f6794ff3e4e2"
    end
  end

  def install
    bin.install "dev-prune"
    # The two names are one binary, and every integration dev-prune writes down — the
    # git hooks, the scheduler — records the path it was invoked from. Installing only
    # one name would make `devp` fail for anyone who read the README.
    bin.install_symlink bin/"dev-prune" => "devp"
    generate_completions_from_executable(bin/"dev-prune", "completions")
  end

  test do
    # `DEV_PRUNE_NO_AUTO_SETUP` because nothing may install itself during a formula
    # test: Homebrew's sandbox would fail the build, and a test that registers a
    # scheduled task on someone's machine is worse than no test at all.
    ENV["DEV_PRUNE_NO_AUTO_SETUP"] = "1"
    assert_match version.to_s, shell_output("#{bin}/dev-prune --version")
    assert_match version.to_s, shell_output("#{bin}/devp --version")
  end
end
